const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { SessionStore, SessionRecorder } = require('../sessions')
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'esco-history-unit-'))
const store = new SessionStore(dir)
const r = new SessionRecorder(store, () => {}, e => { throw e })
const runner = { sessionId: 'sdk-first', sessionCwd: 'C:/work' }
r.begin('見積書を 作って', 'docs', 'C:/work')
const first = r.session.id
r.event('agent:token', { delta: '確認' }, runner)
r.event('agent:token', { delta: 'しました' }, runner)
r.event('agent:tool', { tool: 'Read' }, runner)
r.event('agent:token', { delta: '完成です' }, runner)
r.finish(runner)
assert.equal(store.read(first).messages[1].text, '確認しました')
assert.equal(store.read(first).messages[2].text, '完成です')
assert.equal(store.read(first).sessionId, 'sdk-first')
r.use(store.create())
r.begin('別の会話', 'chat', null)
r.event('agent:error', { message: 'テストエラー' }, { sessionId: null })
r.flush()
assert.equal(store.list().length, 2)
const reopened = new SessionStore(dir).read(first)
assert.equal(reopened.mode, 'docs')
assert.equal(reopened.workFolder, 'C:/work')
assert.equal(reopened.messages.length, 3)
r.use(reopened)
r.begin('続きです', 'docs', 'C:/work')
r.event('agent:text', { text: '続きを回答' }, runner)
r.finish(runner)
assert.equal(store.read(first).messages.length, 5)
assert.throws(() => store.read('../settings'))
fs.writeFileSync(path.join(dir, 'broken.json'), 'invalid json')
assert.equal(store.list().length, 2)
const brokenStore = { create: () => store.create(), save: () => { throw new Error('disk full') } }
let warned = false
const failure = new SessionRecorder(brokenStore, () => {}, () => { warned = true })
assert.throws(() => failure.begin('保存失敗', 'chat', null), /disk full/)
assert.ok(warned)
console.log('PASS: session persistence, restart, independent chats, stream segments, resume metadata, errors, invalid paths, damaged entry isolation')
