const assert = require('node:assert/strict')
const fs = require('fs'), os = require('os'), path = require('path')
const { BusinessStore } = require('../business')
const { ProjectStore } = require('../projects')
const { FolderQueue } = require('../folderQueue')
async function main() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(),'esco-workspace-unit-'))
  const share = path.join(root,'share'); fs.mkdirSync(share)
  const config = {userName:'テスト担当',staffId:'test-staff',businessFolder:share}
  const business = new BusinessStore(path.join(root,'local'), () => config)
  const id = business.capture('毎月請求書を作り、2時間かかる', 'session')
  assert.equal(business.integrate('invalid response',id), false)
  const result = facts => '```json\n'+JSON.stringify({escoBusiness:1,jobs:[{id:'',title:'請求書作成',facts,unknown:['入力資料'],ideas:['転記を自動化']}]})+'\n```'
  business.integrate(result(['毎月作成','2時間']),id)
  await business.sync()
  const files = fs.readdirSync(path.join(share,'スタッフ','test-staff','業務'))
  assert.equal(files.length,1)
  const jobFile = path.join(share,'スタッフ','test-staff','業務',files[0])
  fs.appendFileSync(jobFile,'\n人が書いた追記は残す\n')
  business.integrate(result(['毎月作成','2時間','上司の確認が必要']),id)
  await business.sync()
  assert.ok(fs.readFileSync(jobFile,'utf8').includes('人が書いた追記は残す'))
  assert.ok(fs.readFileSync(jobFile,'utf8').includes('上司の確認が必要'))
  assert.equal(fs.readdirSync(path.dirname(jobFile)).length,1)
  assert.ok(fs.existsSync(path.join(share,'スタッフ','test-staff','_更新履歴')))
  const source = fs.readFileSync(jobFile,'utf8').replace('2時間','1時間（直接編集）'); fs.writeFileSync(jobFile,source)
  business.integrate(result(['毎月作成','2時間','新しい情報']),id)
  await business.sync()
  assert.equal(fs.readFileSync(jobFile,'utf8'),source)
  assert.match(business.status().status,/変更されています/)
  config.businessFolder = path.join(root,'offline')
  business.capture('回線切断中の入力', 'session')
  await business.sync()
  assert.match(business.status().status,/共有待ち/)
  assert.equal(new BusinessStore(path.join(root,'local'),()=>config).state.entries.length,2)
  fs.mkdirSync(config.businessFolder); await business.sync()
  assert.ok(fs.existsSync(path.join(config.businessFolder,'スタッフ','test-staff','入力記録.md')))
  const projects = new ProjectStore(path.join(root,'projects'))
  const p = projects.save({name:'請求業務',folder:share,instructions:'ルール'})
  assert.equal(projects.get(p.id).instructions,'ルール')
  assert.throws(()=>projects.get('../bad'))
  const queue = new FolderQueue()
  const a = queue.request(share), b = queue.request(path.join(share,'child')), c = queue.request(path.join(root,'other'))
  const doneA = await a.wait, doneC = await c.wait
  let gotB = false; b.wait.then(()=>{gotB=true})
  await new Promise(r=>setImmediate(r)); assert.equal(gotB,false)
  doneA(); const doneB = await b.wait; assert.ok(gotB); doneB(); doneC()
  const d = queue.request(share), e = queue.request(share); const stopped = assert.rejects(e.wait,/停止/); e.cancel(); await stopped; (await d.wait)()
  console.log('PASS: business MD overwrite, raw input durability, backups, manual notes, conflict detection, offline/reconnect, project persistence, folder queue/cancel')
}
main().catch(e=>{console.error(e);process.exitCode=1})
