'use strict'
const $=id=>document.getElementById(id), desktop=!!window.escoWorkspace
let state=null, current=null, selectedProject=null, user=null, refreshing=false, workerBusy=false, editing=false, treeDrawn=false, inviteCode=null, treeSignature=null
const labels={queued:'実行待ち',running:'作業中',approval:'確認待ち',done:'完了',failed:'エラー',cancelled:'停止済み',interrupted:'中断・結果の確認が必要'}
const id=()=>crypto.randomUUID(), note=t=>{$('notice').textContent=t||''}
async function api(action,body={}){if(desktop)return window.escoWorkspace.request(action,body);const r=await fetch('api.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});let j;try{j=await r.json()}catch{throw Error('サーバーへ接続できませんでした')}if(!r.ok){if(r.status===401)showLogin();throw Error(j.error||'処理に失敗しました')}return j}
const mutate=(a,b={})=>api(a,{opId:id(),...b})
const draftKey=()=>user&&current?'esco-draft:'+user.id+':'+current.id:null
function draftSave(){const k=draftKey();if(k)try{localStorage.setItem(k,$('input').value)}catch{note('下書きを端末へ保存できません。送信するまで画面を閉じないでください。')}}
function showLogin(){user=null;state=null;current=null;$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;$('messages').replaceChildren();$('input').value=''}
function signedIn(u){treeDrawn=false;treeSignature=null;user=u;$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('who').textContent=u.name+' / 同期ワークスペース';$('driveSetup').hidden=!u.admin;$('inviteStaff').hidden=!u.admin;for(const n of ['qr','import','bind'])$(n).hidden=!desktop}
function button(label,fn,cls=''){const b=document.createElement('button');b.textContent=label;b.type='button';b.className=cls;b.onclick=()=>Promise.resolve().then(fn).catch(e=>note(e.message));return b}
function field(label,value,kind='input'){const wrap=document.createElement('label');wrap.textContent=label;const el=document.createElement(kind);el.value=value||'';wrap.append(el);return {wrap,el}}
function dialog(title,build,save){$('editTitle').textContent=title;$('editBody').replaceChildren();build($('editBody'));$('editSave').hidden=!save;$('editSave').onclick=async()=>{try{await save();$('edit').close();await refresh()}catch(e){note(e.message)}};$('edit').showModal()}
async function refresh(){if(refreshing||!user)return;refreshing=true;try{state=await api('bootstrap');renderTree();$('businessStatus').textContent=state.business||'';const pcValue=$('pc').value;$('pc').replaceChildren();for(const p of state.pcs){const o=document.createElement('option');o.value=p.id;o.textContent=p.name+(p.online?'（接続中）':'（停止中・起動後に実行）');$('pc').append(o)}if(state.pcs.some(p=>p.id===pcValue))$('pc').value=pcValue;if(current){const x=await api('session.get',{id:current.id});const changed=x.revision!==current.revision;current=x;if(changed)renderMessages();renderTask()}note('')}catch(e){note(e.message+'。入力した下書きはこの端末に保持します。')}finally{refreshing=false}}
function renderTree(){const signature=JSON.stringify([state.sessions,state.projects,$('filter').value,current?.id]);if(signature===treeSignature)return;treeSignature=signature;const open=new Set([...$('tree').querySelectorAll('details[open]')].map(d=>d.dataset.id));$('tree').replaceChildren();const f=$('filter').value;const visible=state.sessions.filter(s=>f==='deleted'?s.deleted:f==='archived'?s.archived&&!s.deleted:!s.deleted&&!s.archived).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt.localeCompare(a.updatedAt));for(const p of [{id:null,name:'プロジェクトなし'},...state.projects]){const rows=visible.filter(s=>s.projectId===p.id);const d=document.createElement('details');d.dataset.id=p.id||'';d.open=open.has(d.dataset.id)||!treeDrawn;const head=document.createElement('summary');head.textContent=p.name+' ('+rows.length+')';head.onclick=()=>{selectedProject=p.id};d.append(head);if(p.id)d.append(button('プロジェクト設定',()=>editProject(p),'project-edit'));for(const s of rows)d.append(button((s.pinned?'★ ':'')+s.title,()=>select(s.id),'session'+(current?.id===s.id?' selected':'')));$('tree').append(d)}treeDrawn=true}
async function select(sessionId){draftSave();current=await api('session.get',{id:sessionId});selectedProject=current.projectId;$('input').value=localStorage.getItem(draftKey())||'';$('sidebar').classList.remove('open');renderMessages();renderTask();renderTree()}
function renderMessages(){const near=$('messages').scrollHeight-$('messages').scrollTop-$('messages').clientHeight<90;$('title').textContent=current.title;$('manage').hidden=false;$('projectInfo').textContent=state.projects.find(p=>p.id===current.projectId)?.name||'プロジェクトなし';$('messages').replaceChildren();for(const m of current.messages){const el=document.createElement('div');el.className='msg '+m.role;el.textContent=current.kind==='business'?m.text.replace(/```json\s*[\s\S]*?```/g,'').trim():m.text;$('messages').append(el)}if(near)$('messages').scrollTop=$('messages').scrollHeight;$('route').disabled=current.kind==='business';if(current.kind==='business')$('route').value='cloud';$('pcRow').hidden=$('route').value!=='pc'}
function renderTask(){const tasks=state.tasks.filter(t=>t.sessionId===current.id);const t=tasks.at(-1);const active=t&&['queued','running','approval'].includes(t.status);$('send').disabled=!!active||current.deleted||current.archived||current.purged;$('cancelTask').hidden=!active;$('taskState').textContent=t?(labels[t.status]||t.status)+(t.error?'：'+t.error:''):'';$('asks').replaceChildren();for(const a of Object.values(t?.asks||{})){if(a.answer||!active)continue;const card=document.createElement('section');card.className='ask';const title=document.createElement('b');title.textContent=a.kind==='permission'?'PC上の操作を許可しますか？':a.description;card.append(title);const detail=document.createElement('pre');detail.textContent=[a.tool,a.description,a.detail,JSON.stringify(a.input||{},null,2)].filter(Boolean).join('\n');card.append(detail);const answer=async body=>{await mutate('task.answer',{taskId:t.id,requestId:a.requestId,...body});await refresh()};if(a.kind==='permission'){card.append(button('許可',()=>answer({approved:true})),button('拒否',()=>answer({approved:false})))}else{for(const o of a.options||[])card.append(button(typeof o==='string'?o:o.label,()=>answer({answer:typeof o==='string'?o:o.label})));const f=field('回答','');card.append(f.wrap,button('回答する',()=>answer({answer:f.el.value})))}$('asks').append(card)}}
function editProject(p){let name,instructions;dialog(p?'プロジェクト設定':'新しいプロジェクト',root=>{name=field('プロジェクト名',p?.name);instructions=field('共通の指示',p?.instructions,'textarea');root.append(name.wrap,instructions.wrap)},async()=>{const v=await mutate('project.save',{...(p?{id:p.id,revision:p.revision}:{}),name:name.el.value,instructions:instructions.el.value});selectedProject=v.id})}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await api(inviteCode?'invite.redeem':'login',{url:$('url').value,code:inviteCode,name:$('name').value,email:$('email').value,password:$('password').value});$('password').value='';inviteCode=null;signedIn(r.user);await refresh()}catch(e){note(e.message)}}
$('logout').onclick=async()=>{try{draftSave();await api('logout');showLogin()}catch(e){note(e.message)}}
$('input').oninput=draftSave;$('menu').onclick=()=>$('sidebar').classList.toggle('open');$('filter').onchange=renderTree;$('route').onchange=()=>{$('pcRow').hidden=$('route').value!=='pc'}
$('newProject').onclick=()=>editProject(null)
async function create(kind='chat'){const s=await mutate('session.create',{projectId:kind==='business'?null:selectedProject,kind});await refresh();await select(s.id)}
$('newSession').onclick=()=>create().catch(e=>note(e.message));$('business').onclick=async()=>{try{const s=state.sessions.find(s=>s.kind==='business'&&!s.deleted&&!s.archived);s?await select(s.id):await create('business')}catch(e){note(e.message)}}
$('manage').onclick=()=>{const x={...current};dialog('会話の管理',root=>{const title=field('会話名',x.title);root.append(title.wrap,button('名前を保存',async()=>{await mutate('session.update',{id:x.id,revision:x.revision,title:title.el.value});$('edit').close();await refresh()}));const project=field('所属プロジェクト','','select');for(const p of [{id:'',name:'プロジェクトなし'},...state.projects]){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;project.el.append(o)}project.el.value=x.projectId||'';root.append(project.wrap,button('移動',()=>update({projectId:project.el.value||null})));async function update(body){await mutate('session.update',{id:x.id,revision:x.revision,...body});$('edit').close();await refresh()};root.append(button(x.pinned?'ピン留めを解除':'ピン留め',()=>update({pinned:!x.pinned})),button(x.archived?'アーカイブから戻す':'アーカイブ',()=>update({archived:!x.archived})),button(x.deleted?'ゴミ箱から復元':'ゴミ箱へ移動',()=>update({deleted:!x.deleted})));if(x.deleted)root.append(button('完全削除',async()=>{if(!confirm('この会話を完全に削除します。元に戻せません。共有済みの業務MDは残ります。'))return;await mutate('session.purge',{id:x.id,revision:x.revision,confirmed:true});current=null;$('messages').replaceChildren();$('title').textContent='会話を選択してください';$('manage').hidden=true;$('edit').close();await refresh()}))})}
$('sendForm').onsubmit=async e=>{e.preventDefault();if(!current)return;const text=$('input').value.trim();if(!text)return;const key='esco-pending:'+user.id+':'+current.id;try{let body=JSON.parse(localStorage.getItem(key)||'null');if(body&&body.text!==text)throw Error('前の送信の結果が未確認です。前の内容に戻して再送するか、会話の表示を確認してください。');body||={id:current.id,revision:current.revision,text,route:$('route').value,pcId:$('pc').value,opId:id()};localStorage.setItem(key,JSON.stringify(body));$('send').disabled=true;await api('chat.send',body);localStorage.removeItem(key);$('input').value='';draftSave();await refresh();runWorker()}catch(e){if(/他の端末|処理中|復元|入力|長く/.test(e.message))localStorage.removeItem(key);note(e.message);$('send').disabled=false}}
$('cancelTask').onclick=async()=>{try{const t=state.tasks.filter(t=>t.sessionId===current.id&&['queued','running','approval'].includes(t.status)).at(-1);if(t)await mutate('task.cancel',{taskId:t.id});await refresh()}catch(e){note(e.message)}}
$('bind').onclick=async()=>{try{await api('bind',{projectId:current?.projectId||selectedProject});note('このPCの実行フォルダを登録しました。')}catch(e){note(e.message)}}
$('retryBusiness').onclick=async()=>{try{await mutate('business.retry');runWorker();await refresh()}catch(e){note(e.message)}}
$('qr').onclick=async()=>{try{const q=await api('qr');dialog('スマホで読み取ってください',root=>{const p=document.createElement('p');p.textContent='2分間・1回限り有効です。このQRを読み取った端末であなたの会話にアクセスできます。';const img=document.createElement('img');img.src=q.image;img.alt='スマホログイン用QR';root.append(p,img)})}catch(e){note(e.message)}}
$('import').onclick=async()=>{if(!confirm('このPCに保存されている会話を、ログイン中のアカウントへ取り込みます。スマホからも閲覧できるようになります。'))return;try{const r=await api('import');await refresh();note(r.count+'件を取り込みました。')}catch(e){note(e.message)}}
async function runWorker(){if(!user||workerBusy)return;workerBusy=true;try{await api('work.run')}catch(e){note(e.message)}finally{workerBusy=false}}
async function boot(){try{if(desktop){$('urlRow').hidden=false;const s=await api('status');$('url').value=s.url||'https://esco-corp.sakura.ne.jp/esco-works';if(!s.connected)return;signedIn(s.user)}else{const params=new URLSearchParams(location.hash.slice(1));inviteCode=params.get('invite');if(inviteCode){history.replaceState(null,'',location.pathname);$('nameRow').hidden=false;$('name').required=true;$('loginForm').querySelector('button').textContent='アカウントを作成';note('招待されたメールアドレスと名前を入力し、ご自身のパスワードを決めてください。');return}const pair=params.get('pair');if(pair){history.replaceState(null,'',location.pathname);const r=await api('pair.redeem',{code:pair});signedIn(r.user)}else{const s=await api('bootstrap');signedIn(s.user)}}await refresh()}catch(e){showLogin();note(e.message)}}
setInterval(()=>{if(user)refresh()},3000);setInterval(runWorker,8000);boot()

$('inviteStaff').onclick=()=>dialog('社員を招待',root=>{const email=field('招待する社員のメールアドレス','');root.append(email.wrap,button('招待リンクを作成',async()=>{const r=await mutate('invite.issue',{email:email.el.value});const base=desktop?(await api('status')).url:location.origin+location.pathname.replace(/\/$/,'');const out=field('この社員へ渡す招待リンク（24時間・1回限り）',base+'/#invite='+r.code);out.el.readOnly=true;root.append(out.wrap)}))})

$('driveSetup').onclick=()=>dialog('Google共有フォルダの接続',root=>{const url=field('専用Googleスクリプトの接続URL',''),key=field('接続キー','');key.el.type='password';root.append(url.wrap,key.wrap,button('接続設定を保存',async()=>{await api('drive.configure',{url:url.el.value.trim(),key:key.el.value.trim()});key.el.value='';$('edit').close();note('接続設定を保存しました。業務入力の共有保存を確認します。');runWorker()}))})
